In [1]:
import numpy as np

In [2]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

* How many negative numbers are there?

In [12]:
len(a[a < 0])

4

* How many positive numbers are there?

In [11]:
len(a[a > 0])

5

* How many even positive numbers are there?

In [14]:
len(a[(a % 2 == 0)&(a > 0)])

3

* If you were to add 3 to each data point, how many positive numbers would there be?

In [7]:
a_plus_three = (a + 3)
len(a_plus_three[a > 0])

5

In [9]:
a_plus_three

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3, -3,  6, -4])

In [8]:
a_plus_three[a > 0]

array([ 7, 13, 15, 26,  6])

* If you squared each number, what would the new mean and standard deviation be?

In [26]:
a_squared = a ** 2
print('The standard deviation is: ', a_squared.std())
print('The mean is: ', a_squared.mean())

The standard deviation is:  144.0243035046516
The mean is:  74.0


* A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

In [29]:
(a - (a.mean())).mean()

0.0

* Calculate the z-score for each data point. Recall that the z-score is given by:

Z=
(x
-
μ)
/
σ


In [30]:
(a - (a.mean()))/a.std()

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

* Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.


# Life w/o numpy to life with numpy

* Setup 1
`a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]`

# Use python's built in functionality/operators to determine the following:
### Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

### Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

### Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

### Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

### Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

### Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like `[1, 4, 9, 16, 25...]`

### Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

### Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

### What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
* Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
`b = [
    [3, 4, 5],
    [6, 7, 8]
]`

### Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
`sum_of_b = 0
for row in b:
    sum_of_b += sum(row)`

### Exercise 2 - refactor the following to use numpy. 
`min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1]) ` 

### Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
`max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])`


### Exercise 4 - refactor the following using numpy to find the mean of b
`mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))`

### Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
`product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number`

### Exercise 6 - refactor the following to use numpy to find the list of squares 
```squares_of_b = []```
```for row in b:```
    ```for number in row:```
       ```squares_of_b.append(number**2)```


### Exercise 7 - refactor using numpy to determine the odds_in_b
```odds_in_b = []```
```for row in b:```
    ```for number in row:```
        ```if(number % 2 != 0):```
            ```odds_in_b.append(number)```


### Exercise 8 - refactor the following to use numpy to filter only the even numbers
```evens_in_b = []```
`for row in b:`
    `for number in row:`
        `if(number % 2 == 0):`
            `evens_in_b.append(number)`

### Exercise 9 - print out the shape of the array b.

### Exercise 10 - transpose the array b.

### Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

### Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

* Setup 3 

`c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]`

### HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
* Exercise 1 - Find the min, max, sum, and product of c.

### Exercise 2 - Determine the standard deviation of c.

### Exercise 3 - Determine the variance of c.

### Exercise 4 - Print out the shape of the array c

### Exercise 5 - Transpose c and print out transposed result.

### Exercise 6 - Get the dot product of the array c with c. 

### Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

### Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

* Setup 4

`d = [

    [90, 30, 45, 0, 120, 180],
   
    [45, -90, -30, 270, 90, 0],
    
    [60, 45, -45, 90, -45, 180]
]`

### Exercise 1 - Find the sine of all the numbers in d

### Exercise 2 - Find the cosine of all the numbers in d

### Exercise 3 - Find the tangent of all the numbers in d

### Exercise 4 - Find all the negative numbers in d

### Exercise 5 - Find all the positive numbers in d

### Exercise 6 - Return an array of only the unique numbers in d.

### Exercise 7 - Determine how many unique numbers there are in d.

### Exercise 8 - Print out the shape of d.

### Exercise 9 - Transpose and then print out the shape of d.

### Exercise 10 - Reshape d into an array of 9 x 2

`a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]`

#### Use python's built in functionality/operators to determine the following:
* Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

In [1]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [87]:
sum = 0
for i in a:
    sum = sum + i
print(sum)

55


* Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [7]:
for i in range(len(a)):
    min_val = a[0]
    if a[i] < min_val:
        min_val = a[i]
print(min_val)

1


In [4]:
range(len(a))

range(0, 10)

* Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

In [10]:
max_of_a = max(a)
max_of_a

10

* Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

In [14]:
mean_of_a = sum(a)/len(a)
mean_of_a

5.5

* Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

In [17]:
prod = 1
for i in a:
    prod = prod * i
print(prod)

3628800


* Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like `[1, 4, 9, 16, 25...]`

In [29]:
squares = []
for i in a:
    sqr = i * i
    squares.append(sqr)
print(squares)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


* Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

In [36]:
odds_in_a = []
for i in a:
    if i %2 != 0:
        odds_in_a.append(i)

odds_in_a

[1, 3, 5, 7, 9]

* Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

In [38]:
evens_in_a = [ num for num in a if num %2 == 0 ] 
evens_in_a

[2, 4, 6, 8, 10]

### What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
* Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.

`b = [`

    `[3, 4, 5],`
    
    `[6, 7, 8]`
    
`]`




In [1]:
b = [[3, 4, 5], [6, 7, 8]]

In [2]:
for i in b:
    
    print(sum(i))

12
21


In [31]:
for i in b:
    
    print(min(i))

3
6


In [32]:
for i in b:
    
    print(max(i))

5
8


In [3]:
for i in b:
    
    print(sum(i)/len(i))

4.0
7.0


In [5]:
prod = 1
for i in b:
    prod = prod * i
print(prod)

TypeError: can't multiply sequence by non-int of type 'list'

### Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
`sum_of_b = 0
for row in b:
    sum_of_b += sum(row)`



### Exercise 2 - refactor the following to use numpy. 
`min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1]) ` 



### Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
`max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])`




### Exercise 4 - refactor the following using numpy to find the mean of b
`mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))`



### Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
`product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number`



### Exercise 6 - refactor the following to use numpy to find the list of squares 
```squares_of_b = []```
```for row in b:```
    ```for number in row:```
       ```squares_of_b.append(number**2)```




### Exercise 7 - refactor using numpy to determine the odds_in_b
```odds_in_b = []```
```for row in b:```
    ```for number in row:```
        ```if(number % 2 != 0):```
            ```odds_in_b.append(number)```




### Exercise 8 - refactor the following to use numpy to filter only the even numbers
```evens_in_b = []```
`for row in b:`
    `for number in row:`
        `if(number % 2 == 0):`
            `evens_in_b.append(number)`